#!/usr/bin/env python3
  
import sys
import getopt

opts, args = getopt.getopt(sys.argv[1:], '',['help','read','compute','vasp','lammps'])
opts_dic=dict(opts)

if '--help' in opts_dic or (len(opts) == 0 and len(args) == 0):
  print('Usage:')
  print('     step #1 (read data):  pyhma --vasp --read OUTCAR(s)')
  print('     step #2 (compute  ):  pyhma  pyhma.in')
  sys.exit(0)


# if ('--read' not in opts_dic) and ('--vasp' not in opts_dic) and len(args) == 0: #read
#   if len(opts) != 2 or len(args) == 0:
#     print('Usage (read data):  pyhma --vasp --read OUTCAR(s)')
#     sys.exit()
# elif '--vasp' not in opts_dic: #compute
#   if len(opts) != 1 or len(args) != 1:
#     print('Usage (compute):  pyhma --vasp pyhma.in')
#     sys.exit()
# 
# if len(opts) != 2 or len(args) == 0:
#   # reading data
#   if '--read' in opts_dic:
#     print(' Usage: pyhma  [--read]  [--vasp|--lammps]  filenames[OUTCAR|lammps.out]')
#   # computing
#   if '--read' not in opts_dic:
#     print(' Usage: pyhma  [--vasp|--lammps]  pyhma.in')
#   sys.exit()
  
  
filenames = args

if '--read' in opts_dic:
  # read
  from pyhma.read_vasp import Read_VASP
  rd = Read_VASP(*filenames)
  rd.read()
elif 'pyhma.in' in args:
  # compute
  from pyhma.compute_vasp import Compute_VASP
  cv = Compute_VASP()
  cv.compute()
  o = cv.statistics()
  print(o['uah_conv'])



