#!/usr/bin/env python3
  
import sys
import getopt
import time 
 
opts, args = getopt.getopt(sys.argv[1:], '',['readvasp','readlammps','compute','help'])
opts_dic=dict(opts)

if '--help' in opts_dic or (len(opts) == 0 and len(args) == 0):
  print('Usage:')
  print('     Step #1 (read data):  pyhma --readvasp OUTCAR(s)')
  print('     Step #2 (compute)  :  pyhma --compute')
  sys.exit(0)


# if ('--read' not in opts_dic) and ('--vasp' not in opts_dic) and len(args) == 0: #read
#   if len(opts) != 2 or len(args) == 0:
#     print('Usage (read data):  pyhma --vasp --read OUTCAR(s)')
#     sys.exit()
# elif '--vasp' not in opts_dic: #compute
#   if len(opts) != 1 or len(args) != 1:
#     print('Usage (compute):  pyhma --vasp pyhma.in')
#     sys.exit()
# 
# if len(opts) != 2 or len(args) == 0:
#   # reading data
#   if '--read' in opts_dic:
#     print(' Usage: pyhma  [--read]  [--vasp|--lammps]  filenames[OUTCAR|lammps.out]')
#   # computing
#   if '--read' not in opts_dic:
#     print(' Usage: pyhma  [--vasp|--lammps]  pyhma.in')
#   sys.exit()
  
  
filenames = args

if '--readvasp' in opts_dic:
  # read
  from pyhma import ReadVASP
  rv = ReadVASP(*filenames)
  rv.read()
elif '--compute' in opts_dic:
  # compute
  from pyhma import Compute
  comp = Compute()

  #pr = cProfile.Profile()
  #pr.enable()
  comp.run()
  #pr.disable()
  #s = io.StringIO()
  #sortby = SortKey.CUMULATIVE
  #ps = pstats.Stats(pr, stream=s).sort_stats(sortby)
  #ps.print_stats()
  #print(s.getvalue())

  data_ = comp.get_statistics()

  print(data_['uahc'])
  print(data_['uahm'])
  print(data_['dpc'])
  print(data_['dpm'])



