#!/usr/bin/env python3
  
import sys
import getopt
import time 
 
opts, args = getopt.getopt(sys.argv[1:], '',['readvasp','readlammps','compute','help'])
opts_dic=dict(opts)

if '--help' in opts_dic or (len(opts) == 0 and len(args) == 0):
  print('Usage:')
  print('     Step #1 (read data):  pyhma --readvasp OUTCAR1 OUTCAR2 ... ')
  print('     Step #2 (compute)  :  pyhma --compute')
  sys.exit(0)

filenames = args

if '--readvasp' in opts_dic:
  # read
  from pyhma import ReadVASP
  rv = ReadVASP(*filenames)
  rv.read()

elif '--compute' in opts_dic:

  # compute
  from pyhma import Simulation
  sim = Simulation()
  sim.run()
  data = sim.get_statistics()

  print(' Anharmonic energy [eV/atom]:')
  print('  conv.:', data['uahc'])
  print('  hma  :', data['uahm'],'\n')
  print(' Anharmonic pressure [GPa]:')
  print('  conv.:', data['pahc'])
  print('  hma  :', data['pahm'])


